name: Consumer Project
on: [push]

env:
  CONAN_REVISIONS_ENABLED: 1

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - run: mkdir -p consumer/build
      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Check conan version
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          conan --version
      - name: conan install dependencies
        run: |
          rm -rf $HOME/.conan/data/pact_ffi
          export PATH=$PATH:/home/runner/.local/bin
          conan profile new default --detect
          conan remote add pact-foundation https://pactfoundation.jfrog.io/artifactory/api/conan/pactfoundation-conan
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install .. --build missing
        working-directory: consumer/build
        env:
          CC: gcc-9
          CXX: g++-9    
      - name: Build library
        run: |
          cmake ..
          cmake --build .
          cp ../test/example.jpg .
        working-directory: consumer/build
        env:
          CC: gcc-9
          CXX: g++-9
      - name: Run pact-consumer-tests
        run: test/bin/pact-consumer-tests
        working-directory: consumer/build
        env:
          LOG_LEVEL: DEBUG

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - run: mkdir consumer\build
      - run: |
          rm -rf $HOME/.conan/data/pact_ffi
        shell: bash
      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: conan install dependencies Windows
        run: |
          conan remote add pact-foundation https://pactfoundation.jfrog.io/artifactory/api/conan/pactfoundation-conan
          conan install .. --build missing
        working-directory: consumer/build
      - name: Build library Windows
        run: |
          cmake ..
          cmake --build . --config Release
          cp ../test/example.jpg .
        shell: bash
        working-directory: consumer/build
      - name: Run pact-consumer-tests
        run: test/bin/pact-consumer-tests
        working-directory: consumer/build
        env:
          LOG_LEVEL: DEBUG

  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - run: mkdir -p consumer/build
      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Check conan version
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          conan --version
      - name: conan install dependencies
        run: |
          rm -rf $HOME/.conan/data/pact_ffi
          export PATH=$PATH:/home/runner/.local/bin
          conan profile new default --detect
          conan remote add pact-foundation https://pactfoundation.jfrog.io/artifactory/api/conan/pactfoundation-conan
          conan profile update settings.compiler.cppstd=17 default
          conan install .. --build missing
        working-directory: consumer/build
      - name: Build library
        run: |
          cmake ..
          cmake --build .
          cp ../test/example.jpg .
        working-directory: consumer/build
      - name: Run pact-consumer-tests
        run: test/bin/pact-consumer-tests
        working-directory: consumer/build
        env:
          LOG_LEVEL: DEBUG
